name: checkngo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  nfc_manager: ^3.5.0
  provider: ^6.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  csv: ^6.0.0
  share_plus: ^7.2.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - "assets/"
    - "assets/animations/"
